package com.itfactory.exceptions;

/**
 * Custom exception made to handle errors generated by database manipulation requests;
 */

public class DatabaseOperationException extends Exception{

    public DatabaseOperationException(String message) {
        super(message);
    }
}
