//package com.itfactory.exceptions;
//
///**
// * Custom exception made to handle errors generated by inputting faulty values in the interactive console;
// */
//
//public class InvalidReadValueException extends RuntimeException {
//    public InvalidReadValueException() {
//        super("""
//    Error! Please enter a valid input:
//    For id and job id: only whole numbers allowed (ex: 1, 2, 3 etc.);
//    For name and email: only letters allowed;
//    For salary index: only real numbers allowed, from 1 to 3;
//    For base salary: only real numbers allowed, starting from 500;
//    """);
//    }
//
//}
